### ISSUE TITLE
init script failure in stop() with multiple beam processes

### ISSUE THREAD

**Issue by fprimex** [basho/stanchion#47]
"""
The stop() function in the /etc/init.d/stanchion, /etc/init.d/riak and /etc/init.d/riak-cs scripts checks for the RETVAL but pidof is using too general an argument. If there are multiple beam.smp processes running then the script will report a failure.

A better check might be to perform a pgrep with the argument of DAEMON.

```
RETVAL=`pgrep -f $DAEMON`
```

"""

Related:
https://basho.zendesk.com/agent/#/tickets/4127

**Comment by fprimex** [comment]
Note: pgrep is probably not portable across all of the supported CS platforms.

**Comment by jaredmorrow** [comment]
Fixed and will be available in 1.3.1 packages.
