### ISSUE TITLE
403 Forbidden with httpclient

### ISSUE THREAD

**Issue by zhongcy** [basho/stanchion#84]
hi,
I use httpclient to post json to stanchion REST API(port:8085), the http body is bucket json like:{"bucket"="somebucket","requester": "12345"}.   

But the stanchion return 403 Forbidden as the result :

![11](https://cloud.githubusercontent.com/assets/5222309/4057858/5e267e48-2dce-11e4-8381-07528eb7f9dc.JPG)

is there any steps I forgot to do?

**Comment by kuenishi** [comment]
I think you'll need authorzation header, but if you want to create bucket, just hit Riak CS's REST interface with create bucket. Stanchion REST API is for internal use.
