### ISSUE TITLE
How to deploy a stanchion cluster?

### ISSUE THREAD

**Issue by ghost** [basho/stanchion#86]
hello, i have some question about the riak cs cluster with stanchion, i find that a cluster of riak cs only have a single stanchion node. What about stanchion shut down? all the riak cs can not provide service ? how to prevent it from corupting the System?
i hope you can help me .thank you .

**Comment by binarytemple** [comment]
@HelloLin - the best place to ask this question is on the [riak mailing lists](http://lists.basho.com/mailman/listinfo/riak-users_lists.basho.com). The short answer is, yes Stanchion _is_ a single point of failure, but it's failure will only impinge upon certain account creation operations. For high availability, many deployments employ a load balancer such as `haproxy` to keep two stanchion nodes running with only one visible to the Riak CS nodes at any time.
